import re
import itertools
import numpy as np


# Assumes that the diffusion is written on 12th line as is standard
def extract_d(file_name):
    """Extract diffusion coefficient from file generated by 'gmx msd'"""
    with open(file_name) as f:
        diff = float(re.findall('\d+\.\d+|\d+', f.readlines()[11])[0])

    return diff


def extract_msd(file_name):
    """
    Extract msd from a file generated by 'gmx msd'

    returns x, y where x is time axis and y is msd value
    :param str file_name: File generated by 'gmx msd'
    :return: x-axis of time delay and y-axis of msd values in
    standard gmx units
    :rtype: tuple -> `numpy.array` and `numpy.array`
    """
    y = np.array([])
    x = np.array([])
    with open(file_name) as f:
        for line in itertools.islice(f, 21, None):
            time = float(re.findall('\d+\.\d+|\d+', line)[0])
            msd = float(re.findall('\d+\.\d+|\d+', line)[1])
            x = np.append(x, time)
            y = np.append(y, msd)
    return x, y
